import pandas as pd
import numpy as np
from plotnine import *


def plotClusterWaveforms(output, clusterid):
    # After timeVoltage2tibble.R
    # 'output' is generated by 'parallelWindowNPO' and is a list of vectors.
    #
    # Get the 'output' variable by running:
    #   load(file='output.RData')

    if np.isnan(clusterid):
        idx = np.where(np.isnan(output['clusterid']))
    else:
        idx = np.where(output['clusterid'] == clusterid)
    volt = output['waveform'][idx]

    df = pd.DataFrame()
    N = len(volt)
    for idx in np.arange(0, N):
        if len(volt[[idx]]) != 0:
            df = pd.concat(df, pd.DataFrame(g=np.ones(7, dtype='int') * idx, x=np.arange(1, 8),
                                            y=np.array(volt[idx].split(','), dtype='int')))

    # plot
    p = (ggplot(df) + aes(x=df['x'], y=df['y'], group=df['g']) + geom_line(alpha=0.1) + labs(title=clusterid))
    print(p)
